version: '3'

services:
  service:
    container_name: jiucai-service
    image: jiucai-service:${JIUCAI_TAG}
    ports:
      - '8888:8080'
    environment:
      DB_PWD: jiucai
      DB_URL: jdbc:mysql://mysql:3306/jiucai?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    depends_on:
      - db
  db:
    # restart: always
    container_name: mysql
    image: mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: jiucai
      MYSQL_DATABASE: jiucai
    ports:
      - 33069:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
