# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B  package -Dmaven.test.skip=true --file pom.xml
    - name: Copy jar
      run: cp $(find . -name 'mall*.jar') app.jar
    - name: Conventional Changelog Action
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        output-file: "false"
        output-file: 'MY_CUSTOM_CHANGELOG.md'
        release-count: 0
        skip-version-file: 'true'
    - name: Create Release
      uses: ncipollo/release-action@v1
      if: ${{ steps.changelog.outputs.skipped == 'false' }}
      with:
        artifacts: "app.jar"
        tag: ${{ steps.changelog.outputs.tag }}
        body: ${{ steps.changelog.outputs.clean_changelog }}
        token: ${{ secrets.GITHUB_TOKEN }}
